### ISSUE TITLE
User-defined (nonlinear) objective with vectorized variables

### ISSUE THREAD

**Issue by shenkev** [jump-dev/JuMP.jl#2854] opened 2022-01-22 21:37 UTC
(If not possible, then this is a feature request)

Is it possible to use vectorized variables with user-defined objective functions in JuMP for Julia? Like so,

```
model = Model(GLPK.Optimizer)

A = [
    1 1 9 5
    3 5 0 8
    2 0 6 13
]

b = [7; 3; 5]

c = [1; 3; 5; 2]

@variable(model, x[1:4] >= 0)
@constraint(model, A * x .== b)

# dummy functions, could be nonlinear hypothetically
identity(x) = x
C(x, c) = c' * x

register(model, :identity, 1, identity; autodiff = true)
register(model, :C, 2, C; autodiff = true)
@NLobjective(model, Min, C(identity(x), c))
```

This throws the error,

```
ERROR: Unexpected array VariableRef[x[1], x[2], x[3], x[4]] in nonlinear expression. Nonlinear expressions may contain only scalar expression.
```

Which sounds like no. Is there a workaround to this? I believe `scipy.optimize.minimize` is capable of optimizing user-defined objectives with vectorized variables?

**Comment by odow** [comment] 2022-01-22 23:32
See https://jump.dev/JuMP.jl/stable/manual/nlp/#User-defined-functions-with-vector-inputs

You want:
```julia
model = Model(Ipopt.Optimizer)

A = [
    1 1 9 5
    3 5 0 8
    2 0 6 13
]

b = [7; 3; 5]

c = [1; 3; 5; 2]

@variable(model, x[1:4] >= 0)
@constraint(model, A * x .== b)

# dummy functions, could be nonlinear hypothetically
identity(x) = x
C(x, c) = c' * x

my_objective(x...) = C(identitiy(collect(x)), c)
register(model, :my_objective, length(x), my_objective; autodiff = true)
@NLobjective(model, Min, my_objective(x...))
```

In future, please use the community forum for questions like this: https://discourse.julialang.org/c/domain/opt/13

Also asked on SO: https://stackoverflow.com/questions/70817325/user-defined-nonlinear-objective-with-vectorized-variables-in-jump

I'll close this issue because it is not a bug in JuMP. If you have more questions, please post on the forum and we can discuss in more detail there.

**Closed by odow** 2022-01-22 23:32 UTC
