### ISSUE TITLE
Disabling hessian evaluation

### ISSUE THREAD

**Issue by harshangrjn** [jump-dev/JuMP.jl#2983] opened 2022-05-14 04:08 UTC
W.r.t this test, I observe an interesting output for `evaluator.disable_2ndorder` which switches between `true` and `false` for multiple runs of the same file within Julia's REPL. Ideally this has to be `true` always for this test, based on how it is evaluated [here](https://github.com/jump-dev/JuMP.jl/blob/f233dd11677b8164c509ebf4a1be16971933b4cf/src/nlp.jl#L710). Test may need to be updated to also check for `evaluator.disable_2ndorder` if this a bug, in case. https://github.com/jump-dev/JuMP.jl/blob/f233dd11677b8164c509ebf4a1be16971933b4cf/test/nlp.jl#L1118 

Here is the output (using JuMP v1.0.0) for reference: 
```
julia> include("test_2ndorder.jl")
evaluator.disable_2ndorder = false
MOI.features_available(evaluator) = [:Grad, :Jac, :JacVec, :ExprGraph]
4-element Vector{Symbol}:
 :Grad
 :Jac
 :JacVec
 :ExprGraph

julia> include("test_2ndorder.jl")
evaluator.disable_2ndorder = true
MOI.features_available(evaluator) = [:Grad, :Jac, :JacVec, :ExprGraph]
4-element Vector{Symbol}:
 :Grad
 :Jac
 :JacVec
 :ExprGraph

julia> include("test_2ndorder.jl")
evaluator.disable_2ndorder = true
MOI.features_available(evaluator) = [:Grad, :Jac, :JacVec, :ExprGraph]
4-element Vector{Symbol}:
 :Grad
 :Jac
 :JacVec
 :ExprGraph

julia> include("test_2ndorder.jl")
evaluator.disable_2ndorder = false
MOI.features_available(evaluator) = [:Grad, :Jac, :JacVec, :ExprGraph]
4-element Vector{Symbol}:
 :Grad
 :Jac
 :JacVec
 :ExprGraph
```

**Comment by odow** [comment] 2022-05-14 04:12
What are the contents of `"test_2ndorder.jl"`?

**Comment by odow** [comment] 2022-05-14 04:12
Also `evaluator.disable_2ndorder` is an internal variable, so you shouldn't be relying on it for anything.

**Comment by harshangrjn** [comment] 2022-05-14 04:14
Here is the the content: 
```
using JuMP
model = JuMP.Model()
my_f(x, y) = (x - 1)^2 + (y - 2)^2
JuMP.register(model, :my_f, 2, my_f, autodiff = true)
@variable(model, x[1:2])
@NLobjective(model, Min, my_f(x[1], x[2]))
evaluator = JuMP.NLPEvaluator(model)
evaluator = JuMP.NLPEvaluator(model)
@show evaluator.disable_2ndorder
@show MOI.features_available(evaluator)
```

**Comment by harshangrjn** [comment] 2022-05-14 04:17
I needed to disable the hessian based on user requested features for this issue: https://github.com/lanl-ansi/Alpine.jl/issues/176
Of course, initially I thought of directly using the `disable_2ndorder` as it is suppose to handle this. But anyway switched to directly evaluate `MOI.features_available(evaluator)` and check for `:Hess` key in it.

**Comment by odow** [comment] 2022-05-14 04:22
> But anyway switched to directly evaluate MOI.features_available(evaluator) and check for :Hess key in it.

This is what you should do.

I don't actually think this is a bug.

`disable_2ndorder` is set here:
https://github.com/jump-dev/JuMP.jl/blob/f233dd11677b8164c509ebf4a1be16971933b4cf/src/nlp.jl#L710-L730
which gets set here
https://github.com/jump-dev/JuMP.jl/blob/f233dd11677b8164c509ebf4a1be16971933b4cf/src/nlp.jl#L732-L733

So your first `@show` is querying the unset value. Then it gets set by `features_available`, so the second run it queries the set value.

**Comment by odow** [comment] 2022-05-14 04:30
Closing because this is expected behavior. Use `MOI.features_available` to see if the evaluator supports `:Hess`.

**Closed by odow** 2022-05-14 04:30 UTC
Labels: Category: Nonlinear

**Comment by harshangrjn** [comment] 2022-05-14 04:32
Got it! I evaluated it the `MOI.features_available` way and that works fine. Thanks!
