### ISSUE TITLE
Typo in Tutorial Title

### ISSUE THREAD

**Issue by ParadaCarleton** [jump-dev/JuMP.jl#3179] opened 2023-01-08 20:36 UTC
[Section title is just "The."](https://jump.dev/JuMP.jl/stable/manual/variables/#variables)

**Comment by odow** [comment] 2023-01-08 22:12
Nice catch! This seems to be a bug in Documenter.

On our side, the text is correct:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/8177701/211221646-614424b1-5908-43ef-adc2-d3664c2d042a.png">

but in the latest version, it fails to render

<img width="638" alt="image" src="https://user-images.githubusercontent.com/8177701/211221665-faeb8b94-ea6a-4bc3-a6aa-e18488e09f05.png">

It rendered okay in JuMP v1.4 though: https://jump.dev/JuMP.jl/v1.4/manual/variables/#variables

<img width="638" alt="image" src="https://user-images.githubusercontent.com/8177701/211221681-3f359310-b7b0-414a-a612-d6bdb0cc547e.png">

**Comment by odow** [comment] 2023-01-08 22:23
Reproduced upstream: https://github.com/JuliaDocs/Documenter.jl/issues/2010

**Comment by odow** [comment] 2023-01-08 23:11
This should hopefully get fixed soon: https://github.com/JuliaDocs/Documenter.jl/pull/2011.

I'll keep this issue open, because once that PR is merged, we'll need to update the Documenter commit that we are using:
https://github.com/jump-dev/JuMP.jl/blob/102466119e0e32a3d37ba046038b75ea3192386e/docs/make.jl#L2

**Comment by odow** [comment] 2023-01-10 23:29
New upstream PR is https://github.com/JuliaDocs/Documenter.jl/pull/2014

**Comment by odow** [comment] 2023-01-11 02:54
Fixed upstream, so hopefully https://github.com/jump-dev/JuMP.jl/pull/3185 will fix the problem. Thanks for reporting this!

**Closed** 2023-01-11 03:43 UTC
Labels: upstream, Type: Documentation
