### ISSUE TITLE
JuMP.set_silent(model) not working for Ipopt

### ISSUE THREAD

**Issue by ferrolho** [jump-dev/JuMP.jl#2297] opened 2020-07-27 10:57 UTC
For models created with `Ipopt`, the method `set_silent` is not working: the solver still produces and prints output.

**Comment by frapac** [comment] 2020-07-27 11:36
There was already a discussion about that here: https://github.com/jump-dev/Ipopt.jl/issues/183
I think the problem here is caused by a `silent` attribute not being passed when we copy the model from `CachingOptimizer` to Ipopt. A quick solve would be to ensure that `silent` is being passed when we empty the model:
https://github.com/jump-dev/Ipopt.jl/blob/master/src/MOI_wrapper.jl#L380

**Comment by odow** [comment] 2020-07-27 13:24
This is fixed on `master`.

**Closed** 2020-07-27 13:24 UTC
