### ISSUE TITLE
Problematic dirty flag change

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/JuMP.jl#2809] opened 2021-11-19 20:55 UTC
This might be related to #2797 but if the silent attribute is changed in a model it automatically sets the model to dirty and in order occasions that seem to be unpredictable and it breaks `JuMP.value` later

MWE: 

```julia
using JuMP, Ipopt 
m = Model(Ipopt.Optimizer)
m.is_model_dirty # Returns False
JuMP.set_silent(m)
m.is_model_dirty # Return True
```

**Comment by jd-lara** [comment] 2021-11-19 21:15
@odow I can't understand when does the flag gets changed or what causes it to change between creating the model and adding variables.

**Comment by odow** [comment] 2021-11-20 02:02
The flag is set when any part of the model is modified. Do you have an
example of the unpredictability?

**Comment by jd-lara** [comment] 2021-11-20 02:17
In PowerSimulations the flag changes in this order: 

1. False
2. set_silent -> true 
3. Add vars/constraints -> true 
4. Solve -> false 
5. Solve again -> true

**Comment by odow** [comment] 2021-11-20 03:25
What do you mean "Solve again"?

The rule should be simple and predictable:
 * The flag is set to `true` on any modification.
 * It is set to `false` on exit from `optimize!`
https://github.com/jump-dev/JuMP.jl/blob/ded934743b307e6d034d6f26a0d3a442a29fe9ef/src/optimizer_interface.jl#L209

**Comment by odow** [comment] 2021-12-01 03:14
I talked to @jd-lara offline about this. 

Closing because this is likely an issue in PowerSimulations.jl. Catching these hard-to-find bugs is why we added the dirty flag. He will re-open if he can find the cause in PowerSimulations.jl and it's a bug in JuMP.

**Closed by odow** 2021-12-01 03:14 UTC

**Comment by jd-lara** [comment] 2021-12-03 21:30
For future reference the issue is that we do this in PowerSimulations.jl 

1. Solve 
2. read results
3. modify the problem 
4. if simulation = not ended: Go back to 1

So at the end of a simulation, all the problems end up with dirty flags and they can't be queried again.
