### ISSUE TITLE
Add support for new solver QICS

### ISSUE THREAD

**Issue by araujoms** [jump-dev/JuMP.jl#3861] opened 2024-10-25 08:40 UTC
Yesterday a new conic solver was released, QICS, by @kerry-he: https://github.com/kerry-he/qics https://arxiv.org/abs/2410.17803

It is written in Python, but has surprisingly good performance. It also has interesting features, such as proper support for complex numbers, and support for exotic cones (mostly variations of quantum relative entropy).

I think it would be nice to add support for it in JuMP. I'm definitely not doing it myself, I'm just putting this issue up in case someone is looking for work to do.

**Comment by odow** [comment] 2024-10-25 21:05
Anyone interested in doing this is directed to https://jump.dev/MathOptInterface.jl/stable/tutorials/implementing/

The best place to ask for help is the developer chatroom (the `#jump-dev` channel on slack), and we'll be happy to provide advice or review code etc.

The best place to develop a wrapper is in a new repository under your personal account. It does not need to be part of `jump-dev`.

I'm going to close this issue because the JuMP developers have no plans to develop a wrapper, and this is not a bug report or a feature request for JuMP.jl.

@araujoms you might want to post this on the slack channel or on discourse. A few people there might be interested. Most people do not read issues in the JuMP GitHub repository.

**Closed by odow** 2024-10-25 21:05 UTC
