### ISSUE TITLE
Constraint being violated in a nonlinear model

### ISSUE THREAD

**Issue by barpit20** [jump-dev/JuMP.jl#2037] opened 2019-08-22 17:19 UTC
```julia
using JuMP, Ipopt, Random
n = 1_000
rng = MersenneTwister(1234);
data = randn(rng, n)

mle = Model(with_optimizer(Ipopt.Optimizer, print_level = 0));
@NLparameter(mle, problem_data[i = 1:n] == data[i]);
@variable(mle, μ, start = 0.0);
@variable(mle, σ >= 0.0, start = 1.0);
@NLexpression(mle, likelihood, 
(2 * π * σ^2)^(-n / 2) * exp(-(sum((problem_data[i] - μ)^2 for i in 1:n) / (2 * σ^2)))
);
@NLconstraint(mle, μ == σ^2);
@NLobjective(mle, Max, log(likelihood));

optimize!(mle);
```
Solutions for the above model violate the constraint μ = σ^2:
```julia
julia> @show value(μ);
value(μ) = 0.0

julia> @show value(σ)^2;
value(σ) ^ 2 = 1.0
```

One looking for statuses, we get:
```julia
julia> termination_status(mle)
INVALID_MODEL::TerminationStatusCode = 21

julia> primal_status(mle)
UNKNOWN_RESULT_STATUS::ResultStatusCode = 6
```

**Comment by mlubin** [comment] 2019-08-23 02:10
Thanks for the report. This uncovered a serious bug.

**Comment by barpit20** [comment] 2019-08-23 04:25
The above model is slightly different from the one in the examples. If we write it as it is written there, the constraint is satisfied.

```
using JuMP, Ipopt, Random
n = 1_000
rng = MersenneTwister(1234);
data = randn(rng, n)

model = Model(with_optimizer(Ipopt.Optimizer, print_level = 0))
@variable(model, μ, start = 0.0)
@variable(model, σ >= 0.0, start = 1.0)
@NLconstraint(model, μ == σ^2)
@NLobjective(model, Max, n / 2 * log(1 / (2 * π * σ^2)) -
    sum((data[i] - μ)^2 for i in 1:n) / (2 * σ^2)
)
optimize!(model)
```
```
julia> @show value(μ);
value(μ) = 0.6228839414610626

julia> @show value(σ)^2;
value(σ) ^ 2 = 0.6228839414610626
```

**Comment by blegat** [comment] 2019-08-23 11:24
Should be fixed in JuMP master (which requires MOI v0.9.1)

**Comment by odow** [comment] 2019-09-15 01:03
This is still not fixed.

```Julia
(tmp) pkg> st
    Status `/private/tmp/Project.toml`
  [b6b21f68] Ipopt v0.6.0
  [4076af6c] JuMP v0.20.0
  [b8f27783] MathOptInterface v0.9.2

julia> value(μ), value(σ)
(0.0, 1.0)

julia> value(μ) == value(σ)^2
false
```

**Comment by mlubin** [comment] 2019-09-15 03:53
There was a test added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/850. What happened?

**Comment by blegat** [comment] 2019-09-15 14:56
Which value of `n` and `data` are you using ? It seems the value of `μ` and `σ` you get are simply the starting values but I cannot reproduce it.

**Comment by odow** [comment] 2019-09-15 15:31
Oh. The original bug is actually fixed. 

I had just copy-pasted from the first example with `print_level = 0` and didn't check that it actually solved correctly. It's now running into `log(0.0)` from the `exp(-sum(lots of nonnegative numbers))`.

**Closed** 2020-12-03 09:06 UTC
