### ISSUE TITLE
[Question] GPU based linear solver

### ISSUE THREAD

**Issue by amirmm11** [jump-dev/JuMP.jl#3204] opened 2023-01-27 06:58 UTC
Is there any available GPU-based linear solver that JuMP supports?

Thanks

**Comment by blegat** [comment] 2023-01-27 07:02
SCS does: https://github.com/jump-dev/SCS.jl#scs-with-sparse-gpu-indirect-solver-cuda-only

**Comment by odow** [comment] 2023-01-30 22:07
The GPU build of SCS has some problems: https://github.com/jump-dev/SCS.jl/issues/245. 

This project has been developing optimization tools for GPU: https://github.com/exanauts

Other than that, I'm not sure. In most cases, using a GPU does not improve the solution speed.

If you want to discuss further, please post on the community forum: https://discourse.julialang.org/c/domain/opt/13

Closing because this is not a bug in JuMP.

**Closed by odow** 2023-01-30 22:07 UTC
