### ISSUE TITLE
JuMP logo on night/dark theme

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMP.jl#2492] opened 2021-02-20 18:26 UTC
![image](https://user-images.githubusercontent.com/13870065/108604953-b3439380-738f-11eb-9e15-f5ac0e3e9bd5.png)

This is what I get on my phone's github app.
One possible fix is to use a picture with white background...

**Comment by odow** [comment] 2021-04-14 23:33
I made an attempt here: https://github.com/jump-dev/JuMP.jl/pull/2535

But we probably need to add a white outline to the text, if anyone has SVG skills to do so.

**Comment by odow** [comment] 2021-05-02 19:48
Closing as duplicate of https://github.com/jump-dev/JuMP.jl/issues/2581

**Closed by odow** 2021-05-02 19:48 UTC
Labels: Status: Help Wanted, Type: Documentation, good first issue
