### ISSUE TITLE
Method Ambiguity with Extensions to `build_constraint`

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#3330] opened 2023-04-26 15:53 UTC
I recently updated to JuMP `v1.10` and found that it broke InfiniteOpt. In particular, it appears that the methods https://github.com/jump-dev/JuMP.jl/blob/7a72ea731cf66d39fcff492c73a9c25d9c84670b/src/macros.jl#L637-L659
which were added in #3273 now induce `MethodError`s because of the ambiguity that occurs with certain extensions.

An MWE:
```julia
using JuMP

struct MyTag end
struct MyConstr
    con
    extra
end

function JuMP.build_constraint(_error::Function, f, set, ::MyTag; extra = 0)
    con = build_constraint(_error, f, set)
    return MyConstr(con, extra)
end

function JuMP.add_constraint(model::Model, con::MyConstr, name::String = "")
    cref = add_constraint(model, con.con, name)
    model.ext[:extra_values] = (cref, con.extra)
    return cref
end

model = Model()
@variable(model, x)
@constraint(model, x <= 42, MyTag(), extra = 2)
``` 

With `v1.9`, the MWE works. However, with `v1.10`, we incur the `MethodError`:
```julia
ERROR: MethodError: (::JuMP.var"#build_constraint##kw")(::NamedTuple{(:extra,), Tuple{Int64}}, ::typeof(build_constraint), ::JuMP.var"#_error#74"{Tuple{Symbol, Expr, Expr, Expr}, Symbol, LineNumberNode}, ::AffExpr, ::Nonpositives, ::MyTag) is ambiguous. Candidates:
  (::JuMP.var"#build_constraint##kw")(::Any, ::typeof(build_constraint), _error::Function, f, set::Nonpositives, args...) in JuMP at C:\Users\bbgui\.julia\packages\JuMP\pQApG\src\macros.jl:647
  (::JuMP.var"#build_constraint##kw")(::Any, ::typeof(build_constraint), _error::Function, f, set, ::MyTag) in Main at REPL[4]:1
Possible fix, define
  (::JuMP.var"#build_constraint##kw")(::Any, ::typeof(build_constraint), ::Function, ::Any, ::Nonpositives, ::MyTag)
Stacktrace:
 [1] macro expansion
   @ C:\Users\bbgui\.julia\packages\JuMP\pQApG\src\macros.jl:987 [inlined]
 [2] top-level scope
   @ REPL[11]:1
```

One possible workaround is to declare the extension of `build_constraint` for each possible  set type. So in this particular MWE, we need:
```julia
function JuMP.build_constraint(_error::Function, f, set::JuMP.Nonpositives, ::MyTag; extra = 0)
    con = build_constraint(_error, f, set)
    return MyConstr(con, extra)
end
```
However, this seems less then ideal. It would seem better to simply remove `args...; kwargs...` from the methods added in #3273, since these hinder rather than help extensions as I believe was the intention (I don't think these arguments are needed for any methods in JuMP itself).

**Comment by odow** [comment] 2023-04-26 19:59
I feel like I added the `args...` for a reason. Let me take a look.

**Comment by odow** [comment] 2023-04-26 23:20
The splats were need to maintain compat for:
```julia
using JuMP
function JuMP.build_constraint(
    _error::Function,
    f,
    set::MOI.EqualTo{Float64},
    pos_flag::Int;
    kw_flag::Bool,
)
    @show pos_flag, kw_flag
    return JuMP.build_constraint(_error, f, set)
end
model = Model()
@variable(model, x)
@constraint(model, x == 1, 2, kw_flag = true)
```
because although it looks like the splats never get called here:
https://github.com/jump-dev/JuMP.jl/blob/7a72ea731cf66d39fcff492c73a9c25d9c84670b/src/macros.jl#L621-L628
the additional arguments are (very sneakily) added in after the fact later in the macros: 
https://github.com/jump-dev/JuMP.jl/blob/7a72ea731cf66d39fcff492c73a9c25d9c84670b/src/macros.jl#L970-L971

I don't know what a good solution is here. Adding any method in Julia could create ambiguities and there isn't really a way to avoid.

The best we could do is perhaps add a `extension-tests.yml` CI job to JuMP that we can run before a release to check if any extensions broke?

> One possible workaround is to declare the extension of build_constraint for each possible set type.

For now, yes, I think you'll need to do this.

**Comment by odow** [comment] 2023-04-27 01:49
Here's a CI job running https://github.com/jump-dev/JuMP.jl/actions/runs/4815095682

**Comment by odow** [comment] 2023-04-27 21:28
I guess we ran out of time to talk about this in today's call. But I don't know if there is a good way of avoiding this in future, other than running regression tests for extensions.

> I will go ahead and make some boiler-plate code using @eval to cover the various set types.

You shouldn't need everything. Just the `Nonnegatives`, `Nonpositives`, and `Zeros`. You can use `detect_ambiguities` to find candidates:

https://github.com/jump-dev/JuMP.jl/blob/d844afcae4a7c6a5a5a1a07ace757f9457f74efc/test/runtests.jl#L21

**Comment by odow** [comment] 2023-05-01 21:59
Closing because I don't think there much to do here, other than to be more careful in future and run the `extension-tests.yml`.

**Closed by odow** 2023-05-01 21:59 UTC
