### ISSUE TITLE
set_attribute not defined

### ISSUE THREAD

**Issue by sharabhshukla** [jump-dev/JuMP.jl#3290] opened 2023-03-17 03:59 UTC
ERROR: UndefVarError: set_attribute not defined
Stacktrace:
 [1] top-level scope
   @ ~/Documents/tutorials/bonsai_sim/temp_sim/Jumptest/src/user_cuts.jl:16

This is the script that I am running:

using JuMP
import HiGHS
import Random
import MathOptInterface as MOI

model = Model(HiGHS.Optimizer)
@variable(model, x <= 10.5, Int)
@objective(model, Max, x)
function my_callback_function(cb_data)
    x_val = callback_value(cb_data, x)
    con = @build_constraint(x <= floor(x_val))
    MOI.submit(model, MOI.UserCut(cb_data), con)
end
set_attribute(model, MOI.UserCutCallback(), my_callback_function)
set_attribute(model, MOI.Silent(), true)
optimize!(model)

**Comment by odow** [comment] 2023-03-17 07:13
`set_attribute` was added to JuMP v1.9.0:

https://jump.dev/JuMP.jl/stable/release_notes/#[Version-1.9.0](https://github.com/jump-dev/JuMP.jl/releases/tag/v1.9.0)-(March-7,-2023)

If it isn't defined you must be using an older version of JuMP.

The previous syntax was `MOI.set` instead of `set_attribute`.

**Comment by sharabhshukla** [comment] 2023-03-17 07:55
julia> Pkg.status()
Project HelloWorld v0.1.0
Status `C:\Users\shara\Julia_examples\HelloWorld\Project.toml`
  [cd3eb016] HTTP v1.7.4
  [87dc4568] HiGHS v1.5.0
  [4076af6c] JuMP v1.9.0
  [b8f27783] MathOptInterface v1.13.1
  [df9a0d86] Oxygen v1.1.4
  [438e738f] PyCall v1.95.1
⌃ [1fd47b50] QuadGK v2.8.1
  [82193955] SCIP v0.11.12
Info Packages marked with ⌃ have new versions available and may be upgradable.

**Comment by sharabhshukla** [comment] 2023-03-17 07:56
I still get the same error, I am using JuMP v1.9.0

**Comment by blegat** [comment] 2023-03-17 10:51
Did you close Julia and reopen it after updating ?

**Comment by odow** [comment] 2023-03-17 21:50
I cannot reproduce. If you have updated your packages, you need to restart Julia for the change to take effect.

```julia
(tmp) pkg> st
      Status `/private/tmp/Project.toml`
  [87dc4568] HiGHS v1.5.0
  [4076af6c] JuMP v1.9.0
  [9a3f8284] Random

julia> using JuMP

julia> import HiGHS

julia> import Random

julia> model = Model(HiGHS.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: HiGHS

julia> @variable(model, x <= 10.5, Int)
x

julia> @objective(model, Max, x)
x

julia> function my_callback_function(cb_data)
           x_val = callback_value(cb_data, x)
           con = @build_constraint(x <= floor(x_val))
           MOI.submit(model, MOI.UserCut(cb_data), con)
       end
my_callback_function (generic function with 1 method)

julia> set_attribute(model, MOI.UserCutCallback(), my_callback_function)

julia> set_attribute(model, MOI.Silent(), true)

julia> optimize!(model)
ERROR: MathOptInterface.UnsupportedAttribute{MathOptInterface.UserCutCallback}: Attribute MathOptInterface.UserCutCallback() is not supported by the model.
Stacktrace:
```

But note that HiGHS does not support callbacks.

See https://jump.dev/JuMP.jl/stable/manual/callbacks/#Available-solvers

**Comment by odow** [comment] 2023-03-20 23:40
@sharabhshukla was the problem fixed after restarting Julia? If so, I will close this issue. It's not a bug in JuMP.

**Comment by sharabhshukla** [comment] 2023-03-21 01:49
Yeah, the problem was caused by it wax a mixup of using HiGHS, which I believe does not support callback.

and restarting fixed the issue once I changed the solver to Gurobi

**Comment by odow** [comment] 2023-03-21 01:51
> which I believe does not support callback

Correct.

> restarting fixed the issue

Great! I'll close this issue then. 

If you have other questions, please don't hesitate to post on the forum: https://discourse.julialang.org/c/domain/opt/13.

**Closed by odow** 2023-03-21 01:51 UTC
