### ISSUE TITLE
one NLP constraint has lower bound 0.0 and upper bound 0.0.

### ISSUE THREAD

**Issue by lilianping** [jump-dev/JuMP.jl#2909] opened 2022-03-05 08:39 UTC
When I use jump for control, when I do this model, I get an error saying that my constraints have both upper and lower limits. Why is this? 
this is code：
```Julia
# optimizer = Juniper.Optimizer
# nl_solver= optimizer_with_attributes(Ipopt.Optimizer, "print_level" => 0)
# mip_solver = optimizer_with_attributes(GLPK.Optimizer, "output_flag" => false)
# room = Model(optimizer_with_attributes(optimizer, "nl_solver"=>nl_solver, "mip_solver"=>mip_solver))
room = Model(
    optimizer_with_attributes(
        Pavito.Optimizer,
        "mip_solver" => optimizer_with_attributes(GLPK.Optimizer),
        "cont_solver" =>
            optimizer_with_attributes(Ipopt.Optimizer, "print_level" => 0),
    ),
)
#room = Model(Pavito.Optimizer)

T1_0 = 3
T2_0 = 5
T3_0 = 3
T4_0 = 5
n=80
T_out=3
Q = 1
@variables(room, begin
    Δt ≥ 0, (start = 1 / n) # Time step
        # State variables
    0 ≤ T1[1:n] 


    # Control variables
    0 ≤ q1[1:n] ≤ 10, Int

end)
fix(T1[1], T1_0; force = true)

@objective(room, Min, (T1[80]-30)^2+(T1[70]-30)^2+(T1[60]-30)^2+(T1[50]-30)^2)

@NLexpressions(
   room,
    begin
        
        # Time of flight
        t_f, Δt * n
    end
)
for j in 2:n
    @NLconstraint(room, T1[j]==T1[j-1] -(T1[j-1]/267)+(45*q1[j-1])/(267*10))
end
println("Solving...")
optimize!(room)
solution_summary(room)
println("min temp: ", objective_value(room))`

error：
Solving...

MINLP has a quadratic objective, 161 variables (80 integer), 79 nonlinear constraints, 0 quadratic constraints.

Pavito started, using MIP-solver-driven method...
Only one bound per constraint supported by Pavito for NLP constraints but one NLP constraint has lower bound 0.0 and upper bound 0.0.

Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] _bound_set
    @ C:\Users\86198\.julia\packages\Pavito\H744k\src\algorithm.jl:592 [inlined]
  [3] _bound_set
    @ C:\Users\86198\.julia\packages\Pavito\H744k\src\algorithm.jl:587 [inlined]
  [4] add_cuts(model::Pavito.Optimizer, cont_solution::Vector{Float64}, jac_IJ::Vector{Tuple{Int64, Int64}}, jac_V::Vector{Float64}, grad_f::Vector{Float64}, is_max::Bool, callback_data::Nothing)
    @ Pavito C:\Users\86198\.julia\packages\Pavito\H744k\src\algorithm.jl:512
  [5] add_cuts(model::Pavito.Optimizer, cont_solution::Vector{Float64}, jac_IJ::Vector{Tuple{Int64, Int64}}, jac_V::Vector{Float64}, grad_f::Vector{Float64}, is_max::Bool)
    @ Pavito C:\Users\86198\.julia\packages\Pavito\H744k\src\algorithm.jl:492
  [6] optimize!(model::Pavito.Optimizer)
    @ Pavito C:\Users\86198\.julia\packages\Pavito\H744k\src\algorithm.jl:98
  [7] optimize!(b::MathOptInterface.Bridges.LazyBridgeOptimizer{Pavito.Optimizer})
    @ MathOptInterface.Bridges C:\Users\86198\.julia\packages\MathOptInterface\YDdD3\src\Bridges\bridge_optimizer.jl:319
  [8] optimize!(m::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ModelFunctionConstraints{Float64}}}})
    @ MathOptInterface.Utilities C:\Users\86198\.julia\packages\MathOptInterface\YDdD3\src\Utilities\cachingoptimizer.jl:252
  [9] optimize!(model::Model, optimizer_factory::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JuMP C:\Users\86198\.julia\packages\JuMP\klrjG\src\optimizer_interface.jl:185
 [10] optimize! (repeats 2 times)
    @ C:\Users\86198\.julia\packages\JuMP\klrjG\src\optimizer_interface.jl:157 [inlined]
 [11] top-level scope
    @ In[19]:48
 [12] eval
    @ .\boot.jl:360 [inlined]
 [13] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:1094
```

**Comment by odow** [comment] 2022-03-05 09:04
Hi @lilianping,

This error is coming from Pavito, not from JuMP. Pavito doesn't support nonlinear equality constraints. But it looks like your constraint is linear, so try `@constraint` instead of `@NLconstraint`.

I'm going to close this issue because it is not a bug in JuMP. If you have follow-up questions, please post in the community forum, https://discourse.julialang.org/c/domain/opt/13, and I will answer you there. We try to reserve the GitHub issues for bugs and feature requests, and posting on the forum lets other readers benefit as well.

**Closed by odow** 2022-03-05 09:04 UTC
