### ISSUE TITLE
`sum` over a `SparseAxisArray`

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#2428] opened 2021-01-12 20:24 UTC
It would be nice to be able to execute `Base.sum` over a variable defined with a `SparseAxisArray` in a more straightforward fashion (perhaps extending `Base.sum` in the utils.jl file?).

For example:

Given a variable defined as:
```julia
@variable(model, x[i=1:2, j=i:2])
```
You could sum over it doing: 
```julia
sum(x[i,j] for i = 1:2 for j = i:2)
```
However, it would be nicer to be able to remove the second `for`:
```julia
sum(x[i,j] for i = 1:2, j = i:2)
```
(which can't be done due to a `UndefVarError`)

**Comment by odow** [comment] 2021-01-12 22:09
This is base Julia, not JuMP:
```Julia
julia> y = rand(2, 2)
2×2 Array{Float64,2}:
 0.408406  0.337018
 0.188717  0.273776

julia> sum(y[i,j] for i = 1:2, j = i:2)
ERROR: UndefVarError: i not defined
Stacktrace:
 [1] top-level scope at REPL[102]:1
```
If you have triangular indexing, you must specify multiple `for`.

**Comment by odow** [comment] 2021-01-12 23:17
Closing because this is expected behavior.

**Closed by odow** 2021-01-12 23:17 UTC

**Comment by hdavid16** [comment] 2021-01-13 00:05
Yes. I know it's base Julia. It is just feature that would be nice in the context of JuMP since it is common to sum over a variable  that has sparse structure in math programming. So I wasn't sure if it was best to post this here or in Julia. I posted it here since JuMP uses these sparse structures nicely when declaring variables or constraints.

**Comment by odow** [comment] 2021-01-13 01:01
I don't think we want to depart from the Julia syntax, because this will just cause more confusion. JuMP's macros rewrite expressions for performance, not to add subtly different functionality.

You could open an issue in Julia. Here's an example which gets at what is happening:
```Julia
julia> f() = sum(i + j for i=1:2, j=i:2)
f (generic function with 1 method)

julia> @code_lowered f()
CodeInfo(
1 ─      #414 = %new(Main.:(var"#414#415"))
│   %2 = #414
│   %3 = 1:2
│   %4 = Main.i:2
│   %5 = Base.product(%3, %4)
│   %6 = Base.Generator(%2, %5)
│   %7 = Main.sum(%6)
└──      return %7
)

julia> f()
ERROR: UndefVarError: i not defined
Stacktrace:
 [1] f() at ./REPL[127]:1
 [2] top-level scope at REPL[129]:1
```

Relevant issues (might be more, I didn't check thoroughly):
https://github.com/JuliaLang/julia/issues/4867
https://github.com/JuliaLang/julia/issues/15384

**Comment by hdavid16** [comment] 2021-01-13 01:56
Sounds good. Thanks
