### ISSUE TITLE
Test case failure for mutable_arithmetics.jl on power ppc4le platform

### ISSUE THREAD

**Issue by shirodkara** [jump-dev/JuMP.jl#2250] opened 2020-06-08 18:36 UTC
While testing JuMP on ppc4le with the following Pkg.test("JuMP")
The following tests fail:

Test Summary:          | Pass  Broken  Total
mutable_arithmetics.jl | 3810      12   3822

How should I go about trying to debug/fix these ?

I'm using Julia Version 1.5.0-DEV.880 (2020-05-12) on RHEL7 running on ppc4le

**Comment by blegat** [comment] 2020-06-08 19:10
Broken tests are test that we know fail so we mark them as broken so that it does not make CI fail but keep them as a reminder that there is something to fix. So they are not only broken on ppc4le, they are broken on all architecture.
Anyway, the relevant issue is https://github.com/JuliaOpt/MutableArithmetics.jl/issues/44 and any help is welcome :)

**Comment by blegat** [comment] 2020-06-11 07:51
Closing as it's a duplicate of https://github.com/JuliaOpt/MutableArithmetics.jl/issues/44. Let's continue the discussion there

**Closed by blegat** 2020-06-11 07:51 UTC
