### ISSUE TITLE
Error message copyin certain types with copy_model

### ISSUE THREAD

**Issue by chelseas** [jump-dev/JuMP.jl#2828] opened 2021-12-14 08:02 UTC
I received this error message when using the copy_model function:

```
┌ Warning: Skipping the copy of object `:network` due to unsupported type Network. Please open a GitHub issue at https://github.com/jump-dev/JuMP.jl with this message.
└ @ JuMP ~/.julia/packages/JuMP/klrjG/src/copy.jl:157
┌ Warning: Skipping the copy of object `:before_act` due to unsupported type Bool. Please open a GitHub issue at https://github.com/jump-dev/JuMP.jl with this message.
└ @ JuMP ~/.julia/packages/JuMP/klrjG/src/copy.jl:157
┌ Warning: Skipping the copy of object `:bounds` due to unsupported type Vector{Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}}. Please open a GitHub issue at https://github.com/jump-dev/JuMP.jl with this message.
└ @ JuMP ~/.julia/packages/JuMP/klrjG/src/copy.jl:157
```
The Network type comes from this package: https://github.com/sisl/NeuralVerification.jl
Hyperrectangle type is from this package: https://github.com/JuliaReach/LazySets.jl
But it also fails on Bool.

**Comment by odow** [comment] 2021-12-15 00:01
Hi @chelseas that's for the report. 

Do you have a reproducible example? It looks like they (or you) are putting some stuff in the JuMP object dictionary that shouldn't be there.

The error is being thrown from here:
https://github.com/jump-dev/JuMP.jl/blob/59752794521b8c5eddfd5a57c595bb096a4a56b2/src/copy.jl#L163-L176

Extensions should prefer `model.ext[:network] = ...` instead of `model[:network] = ...`.

Extensions can also define an appropriate `getindex`
https://github.com/jump-dev/JuMP.jl/blob/59752794521b8c5eddfd5a57c595bb096a4a56b2/src/copy.jl#L38-L45

**Comment by chelseas** [comment] 2021-12-15 00:16
Ah okay good to know thanks. I will open a bug report in NeuralVerification.jl

**Comment by odow** [comment] 2021-12-15 00:46
From a quick peruse it looks like there are some simple fixes in NeuralVerification.jl that you can make. You probably want to define a new type to store all of the relevant extension data, rather than storing it in a variety of `model[:key]` fields. 

I'll improve the docs slightly in https://github.com/jump-dev/JuMP.jl/pull/2830 and then close this issue.

**Closed** 2021-12-15 01:38 UTC

**Comment by chelseas** [comment] 2022-03-01 06:29
Hi there, I am revisiting this issue because I want to store more things in the model. I want to store a map from Expr objects to JuMP.VariableRef objects. Is there are way to do this using ReferenceMap? I don't see it immediately.
