### ISSUE TITLE
Optimize a quadratic expression with respect to some quadratic Constraints

### ISSUE THREAD

**Issue by matthiashimmelmann** [jump-dev/JuMP.jl#2357] opened 2020-10-21 12:11 UTC
I am working on optimizing the distance function of a point p to an algebraic variety. In short, I am given polynomial equations 

`f_i(x)=0 for i in 1:m`

where `x` is a D-dimensional variable and `m` is the number of equations. This implies we have the optimization problem

`min_x |x-p|^2 s.t. f_i(x)=0 for i in 1:m`

At the moment I assume that `deg(f_i)<=2`. I use Ipopt and my examplatory code with `m=16` and `D=17` looks like 

```
using JuMP
using Ipopt
array=[]
for point in dataPoints
    model = Model(Ipopt.Optimizer)
    @variable(model, y[1:17], start = 0.0)
    @NLobjective(model, Min, sum((y[i]-point[i])^2 for i in 1:length(point)))
    for i in 1:16
        @NLconstraint(model, sum(coefficients[i][j]'*affineVeronese(2,y)[j] for j in 1:length(coefficients[i])) == 0 )
    end
    optimize!(model)
    append!(array,[objective_value(model)])
end
```

Here, `affineVeronese` produces the veronese embedding of degree 2, concattenated with the veronese of degree 1 and concattenated with a constant. It is equivalent to the regular, projective degree 2 veronese embedding and taking the affine patch `{z_0 != 0}` of projective space afterwards. `dataPoints` is a list of lists, containing `N` points of length dimension, i.e. 17 here. `coefficients[i]` contains the coefficients associated to `f_i`.

The error this produces is 

`ERROR: LoadError: *(::GenericQuadExpr,::GenericQuadExpr) is not defined. Are you trying to build a nonlinear problem? Make sure you use @NLconstraint/@NLobjective.`

in the line `@NLconstraint(model,...)`.

How can I make this work?

Thanks a lot for any help, it is appreciated a lot!

**Comment by odow** [comment] 2020-10-22 22:24
Please read the nonlinear documentation: https://jump.dev/JuMP.jl/stable/nlp/

You cannot use affine or quadratic expressions in `@NL` macros. Your `affineVeronese` function should return an `@NLexpression` object instead.

Closing because this is not a bug in JuMP. Please post on the Community Forum (https://discourse.julialang.org/c/domain/opt/13) if you have follow-up questions.

If you post on the forum, please include a reproducible example, which contains all data and functions necessary to run (e.g., `affineVeronese` and `dataPoints`).

**Closed by odow** 2020-10-22 22:24 UTC
