### ISSUE TITLE
Printing NLexpressions

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/JuMP.jl#2287] opened 2020-07-17 15:28 UTC
Printing model constraints with NLexpressions looks like,
```
subexpression[1] - 3.0 ≤ 0
```
In the case of printing the full model it would be convenient to see the NLexpressions as well.

MWE,
```
using JuMP

m = Model()

@variable(m, x)
ex = @NLexpression(m, x^3)
@NLconstraint(m, ex <= 3)

println(m)
```
The output as of JuMP v0.21.3 looks like,
```
Feasibility
Subject to
 subexpression[1] - 3.0 ≤ 0
```

**Comment by mlubin** [comment] 2020-07-17 15:34
This is a duplicate of https://github.com/jump-dev/JuMP.jl/issues/1983.

**Closed by mlubin** 2020-07-17 15:34 UTC
