### ISSUE TITLE
DenseAxisArray with vector of vector of indices

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#2012] opened 2019-07-23 21:22 UTC
```julia
julia> using JuMP

julia> model = Model();

julia> I = [(2, 0)]
1-element Array{Tuple{Int64,Int64},1}:
 (2, 0)

julia> @constraint(model, [(i, j) in I], 1 == 0)
1-dimensional DenseAxisArray{ConstraintRef{Model,C,Shape} where Shape<:AbstractShape where C,1,...} with index sets:
    Dimension 1, Tuple{Int64,Int64}[(2, 0)]
And data, a 1-element Array{ConstraintRef{Model,C,Shape} where Shape<:AbstractShape where C,1}:
 0 = -1.0

julia> I = [[2, 0]]
1-element Array{Array{Int64,1},1}:
 [2, 0]

julia> @constraint(model, [(i, j) in I], 1 == 0)
ERROR: KeyError: key (2, 0) not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] lookup_index at /home/blegat/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:136 [inlined]
 [3] _to_index_tuple at /home/blegat/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:145 [inlined]
 [4] to_index at /home/blegat/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:163 [inlined]
 [5] setindex!(::JuMP.Containers.DenseAxisArray{ConstraintRef{Model,C,Shape} where Shape<:AbstractShape where C,1,Tuple{Array{Array{Int64,1},1}},Tuple{Dict{Array{Int64,1},Int64}}}, ::ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}},ScalarShape}, ::Tuple{Int64,Int64}) at /home/blegat/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:182
 [6] top-level scope at /home/blegat/.julia/dev/JuMP/src/macros.jl:619
```

cc @tweisser

**Comment by odow** [comment] 2021-02-18 02:11
Closing because this now works:
```julia
julia> @constraint(model, [(i, j) in I], 1 == 0)
1-dimensional DenseAxisArray{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}},ScalarShape},1,...} with index sets:
    Dimension 1, Array{Int64,1}[[0, 2]]
And data, a 1-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}},ScalarShape},1}:
 0 = -1.0
```

Although there is still the issue of
```Julia
julia> @variable(model, x[(i, j) in I])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, Array{Int64,1}[[0, 2]]
And data, a 1-element Array{VariableRef,1}:
 x[(0, 2)]

julia> x[(0, 2)]
ERROR: KeyError: key (0, 2) not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] lookup_index at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:145 [inlined]
 [3] _to_index_tuple at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:154 [inlined]
 [4] to_index at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:174 [inlined]
 [5] getindex(::JuMP.Containers.DenseAxisArray{VariableRef,1,Tuple{Array{Array{Int64,1},1}},Tuple{Dict{Array{Int64,1},Int64}}}, ::Tuple{Int64,Int64}) at /Users/oscar/.julia/dev/JuMP/src/Containers/DenseAxisArray.jl:192
 [6] top-level scope at none:0

julia> x[[0, 2]]
x[(0, 2)]
```
but that's a duplicate of #2424.

**Closed by odow** 2021-02-18 02:11 UTC
Labels: JuMPContainer
