### ISSUE TITLE
Sparse Matrix multiplied by variable vector with Julia v1.0.5 and 1.3 

### ISSUE THREAD

**Issue by kaarthiksundar** [jump-dev/JuMP.jl#2163] opened 2020-02-15 23:32 UTC
The code that worked with Julia 1.0.5 does not work with Julia 1.3. 

````
# in julia 1.0.5
julia> using JuMP, GLPK, SparseArrays
julia> glpk_optimizer = JuMP.with_optimizer(GLPK.Optimizer, tm_lim = 100.0, msg_lev = GLPK.OFF)
julia> m = JuMP.Model(glpk_optimizer)
julia> num_variables = 8; 
julia> JuMP.@variable(m, y[i=1:num_variables])
julia> I = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2]; 
julia> J = [1, 2, 3, 3, 4, 4, 5, 5, 6, 6]; 
julia> V = [1, 1, -0.333333, -1.0, -0.666667, 0.0, -1.0, -1.0, -1.0, -1.0];
julia> A = sparse(I, J, V, 8, 2)
julia> A * y
2-element Array{GenericAffExpr{Float64,VariableRef},1}:
 y[1] - 0.33333333333333337 y[3] - 0.6666666666666666 y[4] - y[5] - y[6]
 y[2] - y[3] - y[5] - y[6]   

# in julia 1.3
julia> A * y
ERROR: MethodError: no method matching one(::Type{GenericAffExpr{C,VariableRef} where C})
Closest candidates are:
  one(::Type{Missing}) at missing.jl:103
  one(::BitArray{2}) at bitarray.jl:400
  one(::Missing) at missing.jl:100
  ...
Stacktrace:
 [1] *(::SparseMatrixCSC{Real,Int64}, ::Array{VariableRef,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/SparseArrays/src/linalg.jl:54
 [2] top-level scope at REPL[23]:1
````
Any help is appreciated.

**Comment by odow** [comment] 2020-02-16 00:55
You likely need to do `A * y` in a macro, i.e.,
```Julia
@expression(model, A * y)
```

Much of the default sparse fallbacks don't work well with JuMP because we don't define `one()` and `zero()` for `GenericAffExpr`.

See: https://github.com/JuliaOpt/JuMP.jl/issues/1151

**Comment by blegat** [comment] 2020-02-17 09:34
This might be because the type of the sparse matrix is `SparseMatrixCSC{Real,Int64}` which is not concrete, try `SparseMatrixCSC{Float64,Int64}`.

**Comment by odow** [comment] 2020-04-03 01:50
Still can't reproduce this on JuMP 0.21.2, even with `V = Real[ ... ]`.

```Julia
julia> A * y
2-element Array{GenericAffExpr{Float64,VariableRef},1}:
 y[1] - 0.333333 y[3] - 0.666667 y[4] - y[5] - y[6]
 y[2] - y[3] - y[5] - y[6]                         

julia> typeof(A)
SparseMatrixCSC{Real,Int64}

julia> typeof(y)
Array{VariableRef,1}
```

Can you reproduce? If not, I will close.

**Comment by odow** [comment] 2020-12-06 02:56
Closing as not reproducible. Please re-open if you can find a reproducible example on `JuMP#master`.

**Closed by odow** 2020-12-06 02:56 UTC
Labels: SparseArrays
